
server:
  port: 9090

security.basic.enabled: false

logging.level:
  ru.xxlabaza.test.pcj.balancing.predicate: DEBUG

app:
  metadata:
    balancing:
      rules:
        id-generator:
          "[2.0.0]": 50

---
spring:
  profiles: second

server:
  port: 9091

eureka:
  instance:
    metadataMap:
      version: '1.0.0'

---
spring:
  profiles: third

server:
  port: 9092

eureka:
  instance:
    metadataMap:
      version: '1.1.0'
