
server:
  port: 9090

security.basic.enabled: false

---
spring:
  profiles: second

server:
  port: 9091

eureka:
  instance:
    metadataMap:
      version: '1.0.0'

---
spring:
  profiles: third

server:
  port: 9092

eureka:
  instance:
    metadataMap:
      version: '1.1.0'
