
server:
  port: 9090
  # context-path: /api/v1/facade

security.basic.enabled: false

logging.level:
  ru.xxlabaza.test.pcj.balancing.predicate: DEBUG
  ru.xxlabaza.test.pcj.balancing: DEBUG

# eureka:
#   instance:
#     metadataMap:
#       container.color: blue

app:
  metadata:
    balancing:
      rules:
        id-generator:
          "[2.0.0]": 100

---
spring:
  profiles: second

server:
  port: 9091

eureka:
  instance:
    metadataMap:
      version: '1.0.0'
      # container.color: green

---
spring:
  profiles: third

server:
  port: 9092

eureka:
  instance:
    metadataMap:
      version: '1.1.0'
      # container.color: blue
